<?php
/** @var \Mirasvit\Feed\Helper\Output $outputHelper */
$outputHelper = $this->helper('Mirasvit\Feed\Helper\Output');

?>
<fieldset class="fieldset admin__fieldset">
    <legend class="legend">
        <span><?php echo __('Conditions') ?></span>
    </legend>
</fieldset>

<script>
    require([
        'jquery'
    ], function ($) {
        $.attributes = <?= \Zend_Json_Encoder::encode($outputHelper->getAttributeOptions()) ?>;
        $.patternTypes = <?= \Zend_Json_Encoder::encode($outputHelper->getPatternTypeOptions()) ?>;
        $.attributeUrl = '<?= $this->getUrl('*/*/attribute') ?>';
    });
</script>

<script type="text/x-magento-init">
    <?php echo \Zend_Json_Encoder::encode($block->getJsConfig()) ?>


</script>

<div data-bind="scope: 'dynamic_attribute'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>