<?php
/**
 * @author     Kristof Ringleff
 * @package    Fooman_PdfCore
 * @copyright  Copyright (c) 2015 Fooman Limited (http://www.fooman.co.nz)
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var \Fooman\PdfCore\Block\Pdf\Table $block
 *
 * Note on the use of @noEscape throughout this template
 * html output is allowed by design to allow users to customise their pdfs
 * Before pdf rendering all output is run filtered by @see \Magento\Framework\Filter\Input\MaliciousCode
 */
?>

<?php $numColumns = count($block->getColumns()); ?>
<?php $lineH = 'line-height: 40%; '; ?>
<?php if ($numColumns) : ?>
    <table width="100%" border="0" cellspacing="0" cellpadding="12">
        <?php if ($numColumns && $block->shouldPrintHeader()) : ?>
            <thead>
            <tr style="line-height: 0.7cm;" nobr="true">
                <?php $i = 1; ?>
                <?php foreach ($block->getColumns() as $column) : ?>
                    <?php $isFirst = $i === 1; ?>
                    <?php $isLast = $i === $numColumns; ?>
                    <th style="<?= /* @noEscape */ $block->getHeaderStyle($isFirst, $isLast)?>"
                        align="center"
                        width="<?= /* @noEscape */ $block->getColumnWidthByIndex($column->getIndex()) ?>%"
                    ><strong><?= /* @noEscape */ strtoupper($block->escapeHtml($column->getTitle())) ?></strong></th>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </tr>
            </thead>
        <?php endif; ?>
        <?php $collection = $block->getCollection() ?>
        <?php if ($collection) : ?>
            <?php $numItems = count($collection); ?>
            <?php $j = 1; ?>
            <?php foreach ($collection as $item) : ?>
                <?php $hasExtras = $block->hasExtras($item); ?>
                <?php $rowBgColor = $block->getRowBg($item, $j) ?>
                <?php $isFirstItem = $j === 1; ?>
                <?php $isLastItem = $j === $numItems && !$hasExtras; ?>
                <!-- This empty row adds a bit of space in between line items -->
                <tr bgcolor="<?= /* @noEscape */ $rowBgColor?>">
                    <?php $i = 1; ?>
                    <?php foreach ($block->getColumns() as $column) : ?>
                        <?php $isFirst = $i === 1; ?>
                        <?php $isLast = $i === $numColumns; ?>
                        <td style="<?= /* @noEscape */ $lineH ?>
                        <?= /* @noEscape */ $block->getCellStyle($isFirstItem, false, $isFirst, $isLast) ?>"
                            align="<?= /* @noEscape */ $block->getAlign($isFirst, $isLast) ?>"
                            width="<?= /* @noEscape */ $block->getColumnWidthByIndex($column->getIndex()) ?>%"
                        >&nbsp;</td>
                        <?php $i++; ?>
                    <?php endforeach; ?>
                </tr>
                <tr nobr="true" bgcolor="<?= /* @noEscape */ $rowBgColor?>">
                    <?php $i = 1; ?>
                    <?php foreach ($block->getColumns() as $column) : ?>
                        <?php $isFirst = $i === 1; ?>
                        <?php $isLast = $i === $numColumns; ?>
                        <td style="<?= /* @noEscape */ $block->getCellStyle($isFirstItem, false, $isFirst, $isLast)?>"
                            align="<?= /* @noEscape */ $block->getAlign($isFirst, $isLast) ?>"
                            width="<?= /* @noEscape */ $block->getColumnWidthByIndex($column->getIndex()) ?>%"
                        ><?= /* @noEscape */ $column->getRowField($item) ?></td>
                        <?php $i++; ?>
                    <?php endforeach; ?>
                </tr>
                <?php if ($hasExtras) : ?>
                    <?php $extras = $block->getExtrasAsCollection($item)?>
                    <?php $extrasHtml = $block->getExtraCellHtml($item)?>
                    <?php $numExtras = count($extras); ?>
                    <?php $k = 1; ?>
                    <?php foreach ($extras as $extraItem) :?>
                        <?php $isFirstExtra = $k === 1; ?>
                        <?php $isLastExtra = ($k === $numExtras && !empty($extrasHtml)); ?>
                        <?php $i = 1; ?>
                        <tr nobr="true" bgcolor="<?= /* @noEscape */ $rowBgColor?>">
                            <?php foreach ($block->getColumns() as $column) : ?>
                                <?php $isFirst = $i === 1; ?>
                                <?php $isLast = $i === $numColumns; ?>
                                <td style="<?=
                                /* @noEscape */ $block->getCellStyle($isFirstExtra, false, $isFirst, $isLast) ?>"
                                    align="<?= /* @noEscape */ $block->getAlign($isFirst, $isLast) ?>"
                                    width="<?= /* @noEscape */ $block->getColumnWidthByIndex($column->getIndex()) ?>%"
                                ><?= /* @noEscape */$column->getRowField($extraItem) ?></td>
                                <?php $i++; ?>
                            <?php endforeach; ?>
                        </tr>
                        <?php $k++; ?>
                    <?php endforeach; ?>
                    <?php if (!preg_match('/^\s+$/', $extrasHtml)) : ?>
                        <!-- This empty row adds a bit of space in between line items -->
                        <tr bgcolor="<?= /* @noEscape */ $rowBgColor?>">
                            <?php $i = 1; ?>
                            <?php $isFirstExtra = $k === 1; ?>
                            <?php foreach ($block->getColumns() as $column) : ?>
                                <?php $isFirst = $i === 1; ?>
                                <?php $isLast = $i === $numColumns; ?>
                                <td style="<?=
                                /* @noEscape */ $block->getCellStyle($isFirstExtra, false, $isFirst, $isLast)?>"
                                    align="<?= /* @noEscape */ $block->getAlign($isFirst, $isLast) ?>"
                                    width="<?= /* @noEscape */ $block->getColumnWidthByIndex($column->getIndex()) ?>%"
                                ><?= /* @noEscape */ $isFirst ? $extrasHtml : '&nbsp;'?></td>
                                <?php $i++; ?>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif;?>
                <?php endif; ?>
                <!-- This empty row adds a bit of space in between line items -->
                <tr bgcolor="<?= /* @noEscape */ $rowBgColor?>">
                    <?php $i = 1; ?>
                    <?php foreach ($block->getColumns() as $column) :?>
                        <?php $isFirst = $i === 1; ?>
                        <?php $isLast = $i === $numColumns;?>
                        <td style="<?= /* @noEscape */ $lineH . $block->getCellStyle(false, true, $isFirst, $isLast) ?>"
                            align="<?= /* @noEscape */ $block->getAlign($isFirst, $isLast) ?>"
                            width="<?= /* @noEscape */ $block->getColumnWidthByIndex($column->getIndex()) ?>%"
                        >&nbsp;</td>
                        <?php $i++; ?>
                    <?php endforeach; ?>
                </tr>
                <?php $j++; ?>
            <?php endforeach; ?>
        <?php else : ?>
            <tr>
                <td style="<?= /* @noEscape */ $block->getRowStyle(true, true) ?>"
                    colspan="<?= (int) $numColumns ?>"><?= $block->escapeHtml(__('No Items')) ?></td>
            </tr>
        <?php endif; ?>
    </table>
<?php endif; ?>
