<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php //if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>
            
            <?php $wrapOptions = false; $i=0; ?>
            <?php //foreach ($block->getFilters() as $filter): ?>
                <?php //if ($filter->getItemsCount()): ?>
                    <?php //if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                    
                    <div data-role="collapsible" class="filter-options-item <?php if($i==0): ?>allow active<?php endif; ?>">
                        <div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __("Catégorie") ?></div>
                        <div data-role="content" class="filter-options-content">
                        <div class="main-sidebar-catalog">
                            <ol class="items">
                            <!-- <li><span> All Categories </span> </li> -->
                            <?php
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();                            
                            // $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
                            $catId = 2;  //Parent Category ID
                            $category = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
                            $subCats = $category->getChildrenCategories();
                            $_helper = $this->helper('Magento\Catalog\Helper\Output');
                                foreach ($subCats as $subcat) {
                                    $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
                                    $subcaturl = $subcat->getUrl();       
                                    ?>
                                    
                                    <li class="item1 main-menu">            
                                        
                                            <a class="parent-catagory" href="<?php  echo $subcaturl; ?>">
                                                <span class="item-label123" style="font-weight: bold;"><?php echo $subcat->getName(); ?></span>
                                            </a>
                                                
                                                <?php
                                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();  
                                                $var = $subcat->getId();
                                                $cId = $var;  //Parent Category ID
                                                $subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($cId);
                                                $sscat = $subCategory->getChildrenCategories();
                                                $sscatcount = $subCategory->getChildrenCategories()->count();
                                                if($sscatcount != 0){ echo '<button id="first-btn" class="level1-btn1-'.$subcat->getId().'">+</button>';}
                                                // echo $sscatcount;
                                                $_helper = $this->helper('Magento\Catalog\Helper\Output');                                                
                                                foreach ($sscat as $sscat) { ?>                                                    
                                                    <ul class="child-level-2 <?php echo "main-".$var; ?>" style="display: none;"> 
                                                        <li class="lavel-2-li">
                                                            <a id="btn-add" href="<?php echo $sscat->getUrl(); ?>">
                                                                <?php echo $sscat->getName(); ?>                                                             
                                                            </a>
                                                            
                                                    <?php
                                                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();  
                                                        $lavel3 = $sscat->getId();
                                                        $cIdlevle3 = $lavel3;  //Parent Category ID
                                                        $subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($cIdlevle3);
                                                        $sscat3 = $subCategory->getChildrenCategories();
                                                        $lavel_3 = $subCategory->getChildrenCategories()->count();
                                                        if($lavel_3 != 0){ echo '<button id="secound-btn" class="level2-btn2-'.$sscat->getId().'">+</button>';}
                                                        $_helper = $this->helper('Magento\Catalog\Helper\Output');
                                                    foreach ($sscat3 as $sscategory3) { ?> 
                                                            <ul class="child-level-3 <?php echo "level3-".$lavel3; ?>"  style="padding-left: 20px; display: none;"> 
                                                                <li class="lavel-3-li">
                                                                    <a href="<?php echo $sscategory3->getUrl(); ?>">
                                                                        <?php echo $sscategory3->getName(); ?>                                                             
                                                                    </a>
                                                                </li>   
                                                            </ul>
                                                        <?php } ?>
                                                        
                                                        </li>
                                                    </ul>
                                                <?php } ?>        
                                                
                                    </li>
                              <?php } ?>
                            </ol>
                        </div>
                        </div>
                    </div>
                    <?php $i++; ?>
                <?php //endif; ?>
            <?php //endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    // require([
                    //     'jquery'
                    // ], function ($) {
                    //     $('#layered-filter-block').addClass('filter-no-options');
                    // });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php //endif; ?>
<style type="text/css">
ul.child-level-2 {
    padding-left: 20px;
}

</style>
<script>
require([
    'jquery'
], function ($) {
    // $(document).ready(function() {
        $(".level1-btn1-139").click(function(){           
            $(".main-139").fadeToggle();
        });
        $(".level1-btn1-56").click(function(){           
            $(".main-56").fadeToggle();
        });
        $(".level1-btn1-55").click(function(){           
            $(".main-55").fadeToggle();
        });
        $(".level1-btn1-4").click(function(){           
            $(".main-4").fadeToggle();
        });

        $(".level2-btn2-3").click(function(){           
            $(".level3-3").fadeToggle();
        });
        $(".level2-btn2-7").click(function(){           
            $(".level3-7").fadeToggle();
        });
        $(".level2-btn2-5").click(function(){           
            $(".level3-5").fadeToggle();
        });
        
        $('.level1-btn1-139').on('click', function() {        
          $('.child-level-2:gt(1)').text();        
          $(this).text() === '+' ? $(this).text('-') : $(this).text('+');
        });
        $('.level1-btn1-56').on('click', function() {        
          $('.child-level-2:gt(1)').text();        
          $(this).text() === '+' ? $(this).text('-') : $(this).text('+');
        });
        $('.level1-btn1-55').on('click', function() {        
          $('.child-level-2:gt(1)').text();        
          $(this).text() === '+' ? $(this).text('-') : $(this).text('+');
        });
        $('.level1-btn1-4').on('click', function() {        
          $('.child-level-2:gt(1)').text();        
          $(this).text() === '+' ? $(this).text('-') : $(this).text('+');
        });
        // level-2
        $('.level2-btn2-3').on('click', function() {        
          $('.child-level-3:gt(1)').text();        
          $(this).text() === '+' ? $(this).text('-') : $(this).text('+');
        });
        $('.level2-btn2-7').on('click', function() {        
          $('.child-level-3:gt(1)').text();        
          $(this).text() === '+' ? $(this).text('-') : $(this).text('+');
        });
        $('.level2-btn2-5').on('click', function() {        
          $('.child-level-3:gt(1)').text();        
          $(this).text() === '+' ? $(this).text('-') : $(this).text('+');
        });
        
        $(document).ready(function() {
            var j = 10
            for(var i = 1; i <= j; i++) {
                console.log(i);
            }
        });
        
});
</script>
