<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_EbayMultiAccount
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE(http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */
 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$json = json_encode($objectManager->create('Ced\EbayMultiAccount\Model\Source\Profile\Category\Rootlevel')->toOptionArray());
?>

<script>
    require([
        "jquery",
        "jquery/ui"
    ], function($){

        var json = <?php echo $json; ?>;

        $( "#automplete-2" ).autocomplete({
            source: json,
            autoFocus:true
        });
        $('#ui-id-1').on('click', function() {
            $("#level_0").val($("#automplete-2").val());
            $("#automplete-2").val($("#level_0 option:selected").text());
            $(".ui-helper-hidden-accessible").hide();
        });
        $("#automplete-2").keyup(function(){
            if(this.value == '')
                $(".ui-helper-hidden-accessible").hide();
            else
                $(".ui-helper-hidden-accessible").show();

        });
    });
</script>
<style>
        .ui-widget {
            font-family: Trebuchet MS,Tahoma,Verdana,Arial,sans-serif;
            font-size: 1.1em;
        }
        .ui-menu {
            display: block;
            list-style: outside none none;
            margin: 0;
            outline: medium none;
            padding: 2px;
        }
        .ui-autocomplete {
            cursor: default;
            left: 0;
            position: absolute;
            top: 0;
        }
        .ui-menu .ui-menu-item a {
            display: block;
            font-weight: normal;
            line-height: 1.5;
            min-height: 0;
            padding: 2px 0.4em;
            text-decoration: none;
        }
        .ui-widget-content a {
            color: #333333;
        }
        .ui-autocomplete .ui-state-focus {
            border: 1px solid #fbcb09;
            background: #fdf5ce url('images/ui-bg_glass_100_fdf5ce_1x400.png') 50% 50% repeat-x;
            font-weight: bold;
            color: #c77405;
        }
        .ui-autocomplete {
            background: #eeeeee url("images/ui-bg_highlight-soft_100_eeeeee_1x100.png") repeat-x scroll 50% top;
            border: 1px solid #dddddd;
            color: #333333;
            height: 300px;
            width: 100px;
            overflow: scroll;
        }
</style>
