<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Ced\EbayMultiAccount\Block\Adminhtml\Accounts\Switcher */
?>
<?php if ($accounts = $block->getAccounts()): ?>

<div class="store-switcher store-view">
    <span class="store-switcher-label"><?= /* @escapeNotVerified */ __('Account View:') ?></span>
    <div class="actions dropdown closable">
        <input type="hidden" name="account_switcher" id="account_switcher"
               data-role="account-id" data-param="<?= /* @escapeNotVerified */ $block->getStoreVarName() ?>"
               value="<?= $block->escapeHtml($block->getStoreId()) ?>"
               onchange="switchScope(this);"<?= /* @escapeNotVerified */ $block->getUiId() ?> />
        <button
            type="button"
            class="admin__action-dropdown"
            data-mage-init='{"dropdown":{}}'
            data-toggle="dropdown"
            aria-haspopup="true"
            id="account-change-button">
            <?= /* @escapeNotVerified */ $block->getCurrentSelectionName() ?>
        </button>
        <ul class="dropdown-menu" data-role="accounts-list">
            <?php foreach ($accounts as $account): ?>
                <li class="account-view">
                    <?php if (! $block->isAccountSelected($account)) {
                        ?>
                        <a data-role="account-id" data-value="<?= $block->escapeHtml($account->getId()) ?>" href="#">
                            <?= $block->escapeHtml($account->getAccountCode()) ?>
                        </a>
                        <?php
                    } else {
                        ?>
                        <span><?= $block->escapeHtml($account->getAccountCode()) ?></span>
                        <?php
                    } ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<script>
require([
    'jquery',
    'Magento_Ui/js/modal/confirm'
], function(jQuery, confirm){

    (function($) {
        var $storesList = $('[data-role=accounts-list]');
        $storesList.on('click', '[data-value]', function(event) {
            var val = $(event.target).data('value');
            var role = $(event.target).data('role');
            var switcher = $('[data-role='+role+']');

            event.preventDefault();

            if (!switcher.val() || val != switcher.val()) {
                switcher.val(val).trigger('change'); // Set the value & trigger event
            }
        });
    })(jQuery);

    var scopeSwitcherHandler;

    function switchScope(obj) {
        var switcher = jQuery(obj);
        var scopeId = switcher.val();
        var scopeParams = '';
        if (scopeId) {
            scopeParams = switcher.data('param') + '/' + scopeId + '/';
        }

        if (obj.switchParams) {
            scopeParams += obj.switchParams;
        }

        if ((typeof scopeSwitcherHandler) != 'undefined') {
            var switcherParams = {
                scopeId: scopeId,
                scopeParams: scopeParams,
                useConfirm: <?= (int)$block->getUseConfirm() ?>
            };
            scopeSwitcherHandler(switcherParams);
        } else {

            <?php if ($block->getUseConfirm()): ?>

            confirm({
                content:  "<?= /* @escapeNotVerified */ __('Please confirm scope switching. All data that hasn\'t been saved will be lost.') ?>",
                actions: {
                    confirm: function() {
                        reload();
                    },
                    cancel: function() {
                        obj.value = '<?= $block->escapeHtml($block->getStoreId()) ?>';
                    }
                }
            });

            <?php else: ?>
                reload();
            <?php endif; ?>
        }

        function reload() {
            <?php if (!$block->isUsingIframe()): ?>
            var url = '<?= /* @escapeNotVerified */ $block->getSwitchUrl() ?>' + scopeParams;
            setLocation(url);
            <?php else: ?>
            jQuery('#preview_selected_store').val(scopeId);
            jQuery('#preview_form').submit();

            jQuery('.store-switcher .dropdown-menu li a').each(function() {
                var $this = jQuery(this);

                if ($this.data('role') === 'store-view-id' && $this.data('value') == scopeId) {
                    jQuery('#store-change-button').html($this.text());
                }
            });

            jQuery('#store-change-button').click();
            <?php endif; ?>
        }
    }

    window.scopeSwitcherHandler = scopeSwitcherHandler;
    window.switchScope = switchScope;

});
</script>
<?php endif; ?>
