<?php
$categories = $block->getCategories();
?>
<script>
    require([
        "jquery"
    ], function ($) {

        var categories = <?php echo json_encode($categories); ?>;

        $('body').on('click','#show_attributes', function () {
            console.log('asfs');
            var id = $('#category_id').val();
            showAttribute(id);
        });


        function showAttribute(id) {
            $.ajax({
                url: "<?php echo $this->getUrl('cdiscount/attribute/fetch', ['form_key' => $block->getFormKey()]) ?>",
                type: 'POST',
                data: {
                    'categoryId':id
                },

                showLoader: true, // enable loader


                success: function (response) {
                    if (response.success === true) {
                        try {
                            var result = '';
                            var attributes = response.attributes;
                            if (attributes && Object.keys(attributes).length > 0) {
                                result = CreateTableView(attributes);

                            }

                            $('#attributes').html(result);
                        }
                        catch (err) {
                          console.log(err);
                        }
                    }
                },
                error: function (response) {
                    console.log(response);

                }
            });



        }

        // This function creates a standard table with column/rows
        // Parameter Information
        // objArray = Anytype of object array, like JSON results
        // theme (optional) = A css class to add to the table (e.g. <table class="<theme>">
        // enableHeader (optional) = Controls if you want to hide/show, default is show
        function CreateTableView(objArray, theme, enableHeader) {
            // set optional theme parameter
            if (theme === undefined) {
                theme = {
                    'table': 'data-grid',
                    'td': '',
                    'th': 'data-grid-th',
                    'tr': 'data-row'
                }; //default
            }

            if (enableHeader === undefined) {
                enableHeader = true; //default enable headers
            }

            if (typeof objArray === 'function') {
                return "";
            }
            if (typeof objArray === 'string') {
                return objArray;
            }

            // If the returned data is an object do nothing, else try to parse
            var array = typeof objArray !== 'object' ? JSON.parse(objArray) : new Array(objArray);
            var keys = Object.keys(array[0]);

            var str = '<table class="' + theme.table + '">';

            // table head
            if (enableHeader) {
                str += '<thead><tr class="' + theme.tr + '">';
                for (var index in keys) {
                    if (typeof index === 'number' || typeof index === 'string') {
                        str += '<th scope="col" class="' + theme.th + '">' + keys[index] + '</th>';
                    }
                }
                str += '</tr></thead>';
            }

            // table body
            str += '<tbody>';
            for (var i = 0; i < array.length; i++) {
                str += (i % 2 == 0) ? '<tr class="alt" class="' + theme.tr + '">' : '<tr>';
                for (var index in keys) {
                    var objValue = array[i][keys[index]];

                    // Support for Nested Tables
                    if (typeof objValue === 'object' && objValue !== null) {
                        if (Array.isArray(objValue)) {
                            str += '<td class="' + theme.td + '">';
                            for (var aindex in objValue) {
                                str += CreateTableView(objValue[aindex], theme, true);
                            }
                            str += '</td>';
                        } else {
                            str += '<td class="' + theme.td + '">' + CreateTableView(objValue, theme, true) + '</td>';
                        }
                    } else if(typeof objValue === 'string') {
                        str += '<td class="' + theme.td + '">' + objValue + '</td>';
                    } else if(typeof objValue === 'number') {
                        str += '<td class="' + theme.td + '">' + objValue.toString() + '</td>';
                    } else {
                        str += '<td class="' + theme.td + '"></td>';
                    }
                }
                str += '</tr>';
            }
            str += '</tbody>';
            str += '</table>';

            return str;
        }
    });
</script>

<div style="text-align: center; margin-bottom: 20px">
    <select id="category_id" class="admin__control-select">
        <option value="">Please select a category</option>
        <?php
            foreach ($categories as $category) {
                echo "<option value='{$category['code']}'>{$category['name']} [{$category['id']}]</option>";
            }
        ?>

    </select>

    <button class="primary" id="show_attributes">Show</button>
</div>

<div id="attributes" style="overflow: auto">

</div>


