<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_Cdiscount
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */

?>
<script>
    var CDISCOUNT_ATTRIBUTE_UPDATE_URL = '<?php echo $this->getUrl('cdiscount/profile/UpdateCategoryAttributes', array('_nosid' => true))?>';
    var CDISCOUNT_PROFILE_ID = '<?php echo $this->getProfileId()?>';
</script>