<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Megamenu
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
$menu_id = $block->getMenuId();
$menu = $block->getMenu();
$customerGroups = $block->getCustomerGroups();
$selecteAll = false;

if ($menu->getCustomerGroups() == null) {
    $selecteAll = true;
}
$selectedCustomerGroups = explode(',', $menu->getCustomerGroups());
?>
<select class="admin__control-multiselect required-entry" multiple="" name="customer_groups[]" id="customer_groups" size="6" placeholder="">
    <?php
    foreach ($customerGroups as $groupId => $code) {
        $selected = '';
        if (in_array($groupId, $selectedCustomerGroups) || $selecteAll) {
            $selected = "selected = 'selected'";
        }
        ?>
        <option <?php echo $selected; ?> value="<?php echo $groupId; ?>"><?php echo $code; ?></option>
        <?php
    }
    ?>
</select>