<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Megamenu
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
$selectedOptions = $block->getSelectedOptions();
$name = $block->getName();
$position = $block->getPosition();
$getRandLabel = $block->getRandLabel();
?>

<select class="enable_blocks admin__control-select" name="<?php echo $name; ?>" data-position="<?php echo $position; ?>">
    <option <?php if ($selectedOptions === "0") {
    echo "selected";
} ?> value="0"><?php echo __('No'); ?></option>
    <option <?php if ($selectedOptions === "1") {
    echo "selected";
} ?> value="1"><?php echo __('Yes'); ?></option>
</select>