<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_EbayMultiAccount
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */

?>
<script>
    require([
        "jquery",
    ], function($) {
        $('[name="account_location"]').change(function(){
            var id = $('#account_location').val();
            if (id) {
                getAttributes(id);
            }
        });

        function getAttributes(id) {
            var parameters = {'account_location': id}
            var rurl ='<?php echo $this->getUrl('ebaymultiaccount/accountconfig/updateDetails',array('_nosid'=>true))?>';
            $.ajax({
                url: rurl,
                type: 'POST',
                data: parameters,
                dataType: 'html',
                showLoader: true,
                success: function(response) {
                    $('#alldetails').html(response);
                },
                error: function() {
                    $('#alldetails').html();
                }
            });
        }
    });
</script>