<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Amazon
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright © 2018 CedCommerce. All rights reserved.
 * @license     EULA http://cedcommerce.com/license-agreement.txt
 */
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "amazon-system": {
                        "component": "Ced_Amazon/js/system/dashboard",
                        "config": {
                            "url": "<?= $block->getUrl('amazon/system/sync') ?>"
                         }
                     }
                }
            }
        }
    }


</script>
<div id="amazon-system" class="amazon-system" data-bind="scope: 'amazon-system'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
