<?php
/* @var $block \Ves\PageBuilder\Block\Adminhtml\Menu */
?>
<div class="landofcoder-fue-menu">
    <div class="actions dropdown closable">
        <button type="button" class="admin__action-dropdown" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
            <span class="admin__action-dropdown-text"><?php echo $block->getCurrentItem()['title'] ?></span>
        </button>
        <ul class="dropdown-menu">
            <?php foreach ($block->getMenuItems() as $index => $item): ?>
                <li class="<?php if ($block->isCurrent($index)): ?>current<?php endif; ?> <?php if (isset($item['separator'])): ?>separator<?php endif; ?>">
                    <a href="<?php echo $item['url'] ?>" <?php echo $block->renderAttributes($item) ?>><?php echo $item['title'] ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
