<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Megamenu
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
$selectedOptions = $block->getSelectedOptions();
?>
<select class="selectcolumns admin__control-select">
    <option <?= /* @noEscape */ $selectedOptions['1']; ?> value="1"><?= /* @noEscape */ __('One Column'); ?></option>
    <option <?= /* @noEscape */ $selectedOptions['2']; ?> value="2"><?= /* @noEscape */ __('Two Columns'); ?></option>
    <option <?= /* @noEscape */ $selectedOptions['3']; ?> value="3"><?= /* @noEscape */ __('Three Columns'); ?></option>
    <option <?= /* @noEscape */ $selectedOptions['4']; ?> value="4"><?= /* @noEscape */ __('Four Columns'); ?></option>
    <option <?= /* @noEscape */ $selectedOptions['5']; ?> value="5"><?= /* @noEscape */ __('Five Columns'); ?></option>
</select>