<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Megamenu
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
$pages = $block->getPages();
?>
<ul class="pagemenu">
    <?php
    $count = 1;
    foreach ($pages as $singlePage) {
        ?>
        <li  style="padding: 5px;">
            <input id="menupage<?= /* @noEscape */ $count; ?>" class="addMenu" type="checkbox"
                   data-url="<?= /* @noEscape */ $singlePage->getIdentifier(); ?>"
                   data-objectid="<?= /* @noEscape */ $singlePage->getPageId(); ?>"
                   data-name="<?= /* @noEscape */ $singlePage->getTitle(); ?>"
                   data-id="<?= /* @noEscape */ $singlePage->getPageId(); ?>" data-type="pages">
            <label for="menupage<?= /* @noEscape */ $count; ?>"><?= /* @noEscape */ $singlePage->getTitle(); ?></label>
        </li>
        <?php
        $count++;
    }
    ?>
</ul>