<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Integrator
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright © 2018 CedCommerce. All rights reserved.
 * @license     EULA http://cedcommerce.com/license-agreement.txt
 */
/** @var \Ced\Integrator\Block\Adminhtml\Support\View $block */
?>
<div class="accordion">
    <div class="entry-edit form-inline">
        <div class="section-config">
            <div class="entry-edit-head">
                <div class="entry-edit-head admin__collapsible-block">
                    <span class="entry-edit-head-link" id="amazon-docs-link"></span>
                    <a>Quick Support</a>
                </div>
            </div>
            <div class="fieldset">
                <footer class="container-fluid footer-section">
                    <div class="contact-section">
                        <div class="row">
                            <!--ticket code-->
                            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                <a title="Click Here to Call us Support" href="tel:888-882-0953" target="_blank">
                                    <div class="ticket">
                                        <div class="icon-box">
                                            <div class="image">
                                                <img src="<?php echo $block->getViewFileUrl('Ced_Integrator::images/support.png'); ?>"
                                                     width="100px">
                                            </div>
                                            <div class="txt">
                                                <span class="more-contact" style="font-size: 30px">Call Us</span>
                                                <span class="more-contact" style="font-size: 19px">888-882-0953</span>
                                                <span style="font-size: 17px">USA Toll-Free</span>
                                            </div>
                                        </div>
                                        <div class="clear"></div>
                                    </div>
                                </a>
                            </div>
                            <!--Send Mail codes-->
                            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                <a title="Click Here to Contact us through Mail" href="mailto:jonsnow@cedcommerce.com"
                                   target="_blank">
                                    <div class="mail">
                                        <div class="icon-box">
                                            <div class="image">
                                                <img src="<?php echo $this->getViewFileUrl('Ced_Integrator::images/mail.png'); ?>"
                                                     width="100px">
                                            </div>
                                            <div class="txt">
                                                <span class="mail more-contact" style="font-size: 30px">Send us </span>
                                                <span class="mail more-contact" style="font-size: 26px; font-weight: 600;">an E-mail</span>
                                            </div>
                                        </div>
                                        <div class="clear"></div>
                                    </div>
                                </a>
                            </div>
                            <!--Make Skype Group Codes-->
                            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                <a title="Click to connect with us over skype "
                                   href="https://join.skype.com/DoaeeA6PoN52" target="_blank">
                                    <div class="skype">
                                        <div class="icon-box">
                                            <div class="image">
                                                <img src="<?php echo $this->getViewFileUrl('Ced_Integrator::images/skype.png'); ?>"
                                                     width="100px">
                                            </div>
                                            <div class="txt">
                                                <span class="more-contact" style="font-size: 30px">Connect</span>
                                                <span class="more-contact" style="font-size: 29px; font-weight: 600;">via Skype</span>
                                            </div>
                                        </div>
                                        <div class="clear"></div>
                                    </div>
                                </a>
                            </div>

                        </div>
                </footer>
            </div>
        </div>
    </div>
</div>

<style>
    .icon-box {
        background-color: #ffffff;
        width: 50%;
        float: left;
        height: 150px;
        display: table;
        text-align: center;
    }

    .icon-box .image {
        display: table-cell;
        vertical-align: middle;
        text-align: center;
    }

    .image {
        min-width: 150px;
        padding-left: 5%;
    }

    .txt {
        min-width: 200px;
        margin-top: 37px;
        /*background-color: #fafafa;*/
        text-transform: uppercase;
        vertical-align: middle;
        text-align: left;
        color: #252323;
    }

    .fieldset {
        /*background-color: #fafafa;*/
        padding-bottom: 1%;
    }

    .col-lg-4, .col-md-4, .col-sm-12, .col-xs-12 {
        width: 33%;
    }

    .mail {
        padding-left: 5%;
    }

    .contact-section {
        padding-left: 5%;
    }

    .more-contact {
        padding-left: 1%;
        font-weight: 900;
        font-size: 15px;
    }

    span {
        display: block;
    }
</style>
