<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_EbayMultiAccount
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE(http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */

$element = $block->getElement();
$_htmlId      = 'ebaymultiaccountAttributes';
$_htmlClass   = 'ebaymultiaccountAttributeClass';
$_htmlName    = 'ebaymultiaccount_attributes';
$_readonly    = false;
?>

<div class="field" id="attribute-<?php /* @escapeNotVerified */ echo $_htmlId?>-container" data-attribute-code="<?php /* @escapeNotVerified */ echo $_htmlId?>"
     >
    <div>
        <table class="admin__control-table tiers_table" id="tiers_table">
            <thead>
            <tr>
                <th class="col-customer-group"><?php /* @escapeNotVerified */ echo __('eBay Attribute') ?></th>
                <th class="col-qty required"><?php /* @escapeNotVerified */ echo __('Magento Catalog Attribute') ?></th>
                <th class="col-qty required"><?php /* @escapeNotVerified */ echo __('Default Value') ?></th>
                <th class="col-delete"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
            </tr>
            </thead>
            <tbody id="<?php /* @escapeNotVerified */ echo $_htmlId ?>_container"></tbody>
            <tfoot>
            <tr>
                <td colspan="4" class="col-actions-add"><?php echo $block->getChildHtml('add_button') ?></td>
            </tr>
            </tfoot>
        </table>

        <script>
            require([
                'mage/template',
                "prototype",
                "mage/adminhtml/form"
            ], function (mageTemplate) {

//<![CDATA[
                var ebaymultiaccountAttributeRowTemplate = '<tr>'
                    + '<input type="hidden" value="0" name="<?php echo $_htmlName ?>[<%- data.index %>][required]" id="cat_dependent_<%- data.index %>_ebaymultiaccount_required"" />'
                    + '<input type="hidden" name="<?php echo $_htmlName ?>[<%- data.index %>][ebaymultiaccount_attribute_name]" id="cat_dependent_<%- data.index %>_ebaymultiaccount_attribute_hidden"" />'
                    + '<input type="hidden" name="<?php echo $_htmlName ?>[<%- data.index %>][ebaymultiaccount_attribute_type]" id="cat_dependent_<%- data.index %>_ebaymultiaccount_attribute_type"" />'
                    + '<td><select onclick="return ebaymultiaccountAttributeControl.setEbayMultiAccountAttributeType(this, <%- data.index %>);" class="<?php echo $_htmlClass ?> custgroup required-entry" name="<?php echo $_htmlName ?>[<%- data.index %>][ebaymultiaccount_attribute_name]" id="cat_dependent_<%- data.index %>_ebaymultiaccount_attribute">'

                    <?php foreach ($this->getEbayMultiAccountAttributes() as $optGroup) {
                    $disable = '';
                    if($optGroup['label'] == 'Required Attributes'){
                        $disable = 'disabled="disabled"';
                    }
                    ?>
                    +'<optgroup <?php echo  $disable ?> label="<?php echo $optGroup['label'] ?> ">'
                    <?php
                    foreach ($optGroup['value'] as $_groupId => $_groupName):
                    $attributeEnum = $_groupName['ebaymultiaccount_attribute_enum'];
                    $attributeEnum = implode(',',array_map(
                        function($arg) {
                            return str_replace("\r", "", str_replace("\n", "", trim($arg)));
                        }, explode(',',$attributeEnum)));
                    $attributeEnum = addslashes($attributeEnum);
                     ?>
                    + '<option value="<?php echo addslashes($_groupName['ebaymultiaccount_attribute_name']) ?>" enum_val="<?php echo $attributeEnum; ?>" attribute_type="<?php echo $_groupName['ebaymultiaccount_attribute_type'] ?>"><?php echo __(addslashes($_groupId)) ?></option>'
                    <?php endforeach
                    ?>
                    +'</optgroup>'
                    <?php  }
                    ?>
                    + '</select></td>'
                    + '<td> <select onChange="return ebaymultiaccountAttributeControl.showDefaultField(this, <%- data.index %>);" class="<?php echo $_htmlClass ?> required_magento_attr required-entry" name="<?php echo $_htmlName ?>[<%- data.index %>][magento_attribute_code]" id="cat_dependent_<%- data.index %>_magento_attr">'
                    <?php foreach ($this->getMagentoAttributes() as $_groupId=>$_groupName): ?>
                    + "<option value='<?php echo $_groupId ?>' ><?php echo __($_groupName) ?></option>"
                    <?php endforeach ?>
                    + '</select>'
                    + ' </td>'
                    + '<td><input style="display:none;" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][default]" value="" id="cat_dependent_<%- data.index %>_default_text" />'
                    + '<select  style="display:none;" class="<?php echo $_htmlClass ?> required_magento_attr" name="<?php echo $_htmlName ?>[<%- data.index %>][default]" id="cat_dependent_<%- data.index %>_default_select">'
                    + '</select>'
                    + '<td class="col-delete"><input type="hidden" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][delete]" class="delete" value="" id="cat_dependent_<%- data.index %>_delete" />'
                    + '<button title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Delete Tier')); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="cat_dependent_<%- data.index %>_delete_button" onclick="return ebaymultiaccountAttributeControl.deleteItem(event);">'
                    + '<span><?php /* @escapeNotVerified */ echo __("Delete") ?></span></button></td>'
                    + '</tr>';

                var ebaymultiaccountAttributeControl = {
                    template: mageTemplate(ebaymultiaccountAttributeRowTemplate),
                    itemsCount: 0,
                    addItem : function () {
                        <?php if ($_readonly): ?>
                        if (arguments.length < 5) {
                            return;
                        }
                        <?php endif; ?>
                        var data = {
                            ebaymultiaccount_attribute: '',
                            magento_attr: '',
                            required: '',
                            ebaymultiaccount_attribute_type: '',
                            index: this.itemsCount++,
                            default:''
                        };

                        if(arguments.length >= 5) {
                            data.ebaymultiaccount_attribute = arguments[0];
                            data.magento_attr      = arguments[1];
                            data.ebaymultiaccount_attribute_type      = arguments[2];
                            data.required        = arguments[3];
                            data.default = arguments[4];
                        }
                        

                        Element.insert($('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container'), {
                            bottom : this.template({
                                data: data
                            })
                        });
                        var ebaymultiaccountAttribute = $('cat_dependent_' + data.index + '_ebaymultiaccount_attribute');
                        var magentoAttribute = $('cat_dependent_' + data.index + '_magento_attr');
                        ebaymultiaccountAttribute.value = data.ebaymultiaccount_attribute;
                        magentoAttribute.value    = data.magento_attr;
                        $('cat_dependent_' + data.index + '_ebaymultiaccount_attribute_type').value    = data.ebaymultiaccount_attribute_type;
                        $('cat_dependent_' + data.index + '_ebaymultiaccount_attribute').value = data.ebaymultiaccount_attribute;
                        $('cat_dependent_' + data.index + '_magento_attr').value    = data.magento_attr;
                        $('cat_dependent_' + data.index + '_ebaymultiaccount_attribute_type').value    = data.ebaymultiaccount_attribute_type;

                        if(data.required==1) {
                            $('cat_dependent_' + data.index + '_delete_button').remove();
                            $('cat_dependent_' + data.index + '_ebaymultiaccount_attribute').disabled = true;
                            $('cat_dependent_' + data.index + '_ebaymultiaccount_attribute_hidden').value = data.ebaymultiaccount_attribute;
                            $('cat_dependent_' + data.index + '_ebaymultiaccount_required').value    = data.required;
                        }

                        if (data.readOnly == '1') {
                            ['website', 'cust_group', 'qty', 'price', 'delete'].each(function(idx){
                                $('cat_dependent_'+data.index+'_'+idx).disabled = true;
                            });
                            $('cat_dependent_'+data.index+'_delete_button').hide();
                        }

                        <?php if ($_readonly): ?>
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(this.disableElement);
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button').each(this.disableElement);
                        <?php else: ?>
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(function(el){ Event.observe(el, 'change', el.setHasChanges.bind(el)); });
                        <?php endif; ?>
                        ebaymultiaccountAttributeControl.setEbayMultiAccountAttributeType(ebaymultiaccountAttribute, data.index);
                        if(data.default!=''){
                            var enumVal = ebaymultiaccountAttribute.options[data.index].getAttribute('enum_val');
                            var text = $('cat_dependent_'+data.index+'_default_text');
                            var select = $('cat_dependent_'+data.index+'_default_select');
                            select.value = data.default;
                            text.value = data.default;

                            ebaymultiaccountAttributeControl.showDefaultField(magentoAttribute, data.index);
                        }
                    },
                    disableElement: function(el) {
                        el.disabled = true;
                        el.addClassName('disabled');
                    },
                    deleteItem: function(event) {
                        var tr = Event.findElement(event, 'tr');
                        if (tr) {
                            Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                            Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                            Element.hide(tr);
                            Element.addClassName(tr, 'no-display template');
                        }
                        return false;
                    },
                    showDefaultField: function (e, index) {
                        var checkdefault = e.options[e.selectedIndex].getAttribute('value');
                        var text = $('cat_dependent_'+index+'_default_text');
                        var select = $('cat_dependent_'+index+'_default_select');

                        if(checkdefault == 'default'){
                            var ebaymultiaccountAttribute = $('cat_dependent_' + index + '_ebaymultiaccount_attribute');
                            var enumVal = ebaymultiaccountAttribute.options[ebaymultiaccountAttribute.selectedIndex].getAttribute('enum_val');
                            if(enumVal){
                                select.enable();
                                select.show();
                            }
                            else{
                                text.enable();
                                text.show();
                            }

                        }else{
                            select.hide();
                            text.hide();
                            select.disable();
                            text.disable();
                        }
                    },
                    setEbayMultiAccountAttributeType: function(e, index) {
                        if(e.selectedIndex!=-1){
                            var attributeType = e.options[e.selectedIndex].getAttribute('attribute_type');
                            $('cat_dependent_' + index + '_ebaymultiaccount_attribute_type').value    = attributeType;
                            var enumVal = e.options[e.selectedIndex].getAttribute('enum_val');
                            var text = $('cat_dependent_'+index+'_default_text');
                            var select = $('cat_dependent_'+index+'_default_select');
                            select.hide();
                            text.hide();
                            select.disable();
                            text.disable();

                            if(enumVal){
                                var values = enumVal.split(",");
                                while (select.options.length > 0) {
                                    select.remove(0);
                                }
                                for ( i=0; i<values.length; i++) {
                                    select.insert(new Element('option', {"value": values[i]}).update(values[i]));
                                }
                            }
                        }
                    }
                };
                <?php if(count($this->getMappedAttribute()) > 0 ) {
                foreach ($this->getMappedAttribute() as $_item): 
                    $default = isset($_item['default']) ? $_item['default']: '';
                ?>
                ebaymultiaccountAttributeControl.addItem('<?php echo addslashes($_item['ebaymultiaccount_attribute_name']) ?>', '<?php echo $_item['magento_attribute_code'] ?>', '<?php echo $_item['ebaymultiaccount_attribute_type'] ?>','<?php echo $_item['required'] ?>' ,'<?php echo $default; ?>');
                <?php endforeach; } ?>
                <?php if ($_readonly): ?>
                $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button')
                    .each(ebaymultiaccountAttributeControl.disableElement);
                <?php endif; ?>
                window.ebaymultiaccountAttributeControl = ebaymultiaccountAttributeControl;
//]]>
            });
        </script>
    </div>
    <?php if (!empty($this->getCategoryFeature())) {
        foreach ($this->getCategoryFeature() as $key => $condition) {
            if ($key == 'Condition') {
     ?>
        <div class="field admin__field required _required" data-ui-id="mapping-fieldset-element-select-feature">
            <label class="label admin__field-label" for="feature" data-ui-id="mapping-fieldset-element-select-feature">
                <span>Category Feature</span>
            </label>
            <div class="admin__field-control control">
                <select id="feature" name="feature" title="Category Features" class=" required-entry _required select admin__control-select" data-ui-id="mapping-fieldset-element-select-feature">
                    <option value="">Select Category Feature</option>
                    <?php
                        foreach ($condition as $key =>  $value) {
                            if (!empty($this->getSavedCatFeatures()) && $key == $this->getSavedCatFeatures()) {  ?>
                            <option value="<?php echo $key ?>" selected ="selected"> <?php echo __($value) ?> 
                            </option>
                            <?php  } else { ?>
                            <option value="<?php echo $key ?>"> <?php echo __($value) ?> 
                            </option>
                         <?php }
                        }
                    ?>
                </select>
            </div>
        </div>
    <?php } else { ?>       
            <b><?php echo $condition; ?></b><br><br>
    <?php   }
        }
      }
     ?>
</div>
        
