<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_EbayMultiAccount
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE(http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */

$element = $block->getElement();
$_htmlId      = 'requiredAttributes';
$_htmlClass   = 'requiredAttributeClass';
$_htmlName    = 'required_attributes';
$_readonly    = false;

?>

<div class="field" id="attribute-<?php /* @escapeNotVerified */ echo $_htmlId?>-container" data-attribute-code="<?php /* @escapeNotVerified */ echo $_htmlId?>"
     >
    <div class="control">
        <table class="admin__control-table tiers_table" id="tiers_table">
            <thead>
            <tr>
                <th class="col-customer-group"><?php /* @escapeNotVerified */ echo __('eBay Attribute') ?></th>
                <th class="col-qty required"><?php /* @escapeNotVerified */ echo __('Magento Catalog Attribute') ?></th>
                <th class="col-qty required"><?php /* @escapeNotVerified */ echo __('Default Value') ?></th>
                <th class="col-delete"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
            </tr>
            </thead>
            <tbody id="<?php /* @escapeNotVerified */ echo $_htmlId ?>_container"></tbody>
            <tfoot>
            <tr>
                <td colspan="4" class="col-actions-add"><?php echo $block->getChildHtml('add_button') ?></td>
            </tr>
            </tfoot>
        </table>

        <script>
            require([
                'Magento_Ui/js/modal/modal',
                'mage/template',
                "prototype",
                "mage/adminhtml/form"
            ], function (modal, mageTemplate) {

//<![CDATA[
                var requiredAttributeRowTemplate = '<tr>'
                    + '<input type="hidden" value="0" name="<?php echo $_htmlName ?>[<%- data.index %>][required]" id="tier_price_row_<%- data.index %>_ebaymultiaccount_required"" />'
                    + '<input type="hidden" name="<?php echo $_htmlName ?>[<%- data.index %>][ebaymultiaccount_attribute_name]" id="tier_price_row_<%- data.index %>_ebaymultiaccount_attribute_hidden"" />'
                    + '<input type="hidden" name="<?php echo $_htmlName ?>[<%- data.index %>][ebaymultiaccount_attribute_type]" id="tier_price_row_<%- data.index %>_ebaymultiaccount_attribute_type"" />'
                    + '<td><select onclick="return requiredAttributeControl.setEbayMultiAccountAttributeType(this, <%- data.index %>);" class="<?php echo $_htmlClass ?> custgroup required-entry" name="<?php echo $_htmlName ?>[<%- data.index %>][ebaymultiaccount_attribute_name]" id="tier_price_row_<%- data.index %>_ebaymultiaccount_attribute">'

                    <?php foreach ($this->getEbayMultiAccountAttributes() as $optGroup) {
                    $disable = '';
                    if($optGroup['label'] == 'Required Attributes'){
                        $disable = 'disabled="disabled"';
                    }
                    ?>
                    +'<optgroup <?php echo  $disable ?> label="<?php echo $optGroup['label'] ?> ">'
                    <?php
                    foreach ($optGroup['value'] as $_groupId => $_groupName):
                    $attributeEnum = $_groupName['ebaymultiaccount_attribute_enum'];
                    $attributeEnum = implode(',',array_map(
                        function($arg) {
                            return str_replace("\r", "", str_replace("\n", "", trim($arg)));
                        }, explode(',',$attributeEnum)));
                    $attributeEnum = addslashes($attributeEnum);
                     ?>
                    + '<option value="<?php echo $_groupName['ebaymultiaccount_attribute_name'] ?>" enum_val="<?php echo $attributeEnum; ?>" attribute_type="<?php echo $_groupName['ebaymultiaccount_attribute_type'] ?>"><?php echo __($_groupId) ?></option>'
                    <?php endforeach
                    ?>
                    +'</optgroup>'
                    <?php  }
                    ?>
                    + '</select></td>'
                    + '<td> <select onChange="return requiredAttributeControl.showDefaultField(this, <%- data.index %>);" class="<?php echo $_htmlClass ?> required_magento_attr required-entry" name="<?php echo $_htmlName ?>[<%- data.index %>][magento_attribute_code]" id="tier_price_row_<%- data.index %>_magento_attr">'
                    <?php foreach ($this->getMagentoAttributes() as $_groupId=>$_groupName): ?>
                    + "<option value='<?php echo $_groupId ?>' ><?php echo __($_groupName) ?></option>"
                    <?php endforeach ?>
                    + '</select>'
                    + ' </td>'
                    + '<td><input style="display:none;" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][default]" value="" id="tier_price_row_<%- data.index %>_default_text" />'
                    + '<select  style="display:none;" class="<?php echo $_htmlClass ?> required_magento_attr" name="<?php echo $_htmlName ?>[<%- data.index %>][default]" id="tier_price_row_<%- data.index %>_default_select">'
                    + '</select>'
                    + '<textarea style="display:none;" name="<?php echo $_htmlName ?>[<%- data.index %>][default]" id="tier_price_row_<%- data.index %>_default_textarea" rows="1" cols="20"></textarea>'
                    + '<td class="col-delete"><input type="hidden" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][delete]" class="delete" value="" id="tier_price_row_<%- data.index %>_delete" />'
                    + '<button title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Delete Tier')); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="tier_price_row_<%- data.index %>_delete_button" onclick="return requiredAttributeControl.deleteItem(event);">'
                    + '<span><?php /* @escapeNotVerified */ echo __("Delete") ?></span></button>'
                    + '<button style="display:none;" title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Add MultiAttribute')); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="tier_price_row_<%- data.index %>_add_multiattr_button" row_id="<%- data.index %>" id_prefix="tier_price_row_" onclick="return requiredAttributeControl.mapMultiAttribute(this);">'
                    + '<span><?php /* @escapeNotVerified */ echo __("Add MultiAttribute") ?></span></button></td>'
                    + '</tr>';

                var requiredAttributeControl = {
                    template: mageTemplate(requiredAttributeRowTemplate),
                    itemsCount: 0,
                    addItem : function () {
                        <?php if ($_readonly): ?>
                        if (arguments.length < 5) {
                            return;
                        }
                        <?php endif; ?>
                        var data = {
                            ebaymultiaccount_attribute: '',
                            magento_attr: '',
                            required: '',
                            ebaymultiaccount_attribute_type: '',
                            index: this.itemsCount++,
                            default:''
                        };

                        if(arguments.length >= 5) {
                            data.ebaymultiaccount_attribute = arguments[0];
                            data.magento_attr      = arguments[1];
                            data.ebaymultiaccount_attribute_type      = arguments[2];
                            data.required        = arguments[3];
                            data.default = arguments[4];
                        }
                        

                        Element.insert($('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container'), {
                            bottom : this.template({
                                data: data
                            })
                        });
                        var ebaymultiaccountAttribute = $('tier_price_row_' + data.index + '_ebaymultiaccount_attribute');
                        var magentoAttribute = $('tier_price_row_' + data.index + '_magento_attr');
                        ebaymultiaccountAttribute.value = data.ebaymultiaccount_attribute;
                        magentoAttribute.value    = data.magento_attr;
                        $('tier_price_row_' + data.index + '_ebaymultiaccount_attribute_type').value    = data.ebaymultiaccount_attribute_type;
                        $('tier_price_row_' + data.index + '_ebaymultiaccount_attribute').value = data.ebaymultiaccount_attribute;
                        $('tier_price_row_' + data.index + '_magento_attr').value    = data.magento_attr;
                        $('tier_price_row_' + data.index + '_ebaymultiaccount_attribute_type').value    = data.ebaymultiaccount_attribute_type;

                        if(data.required==1) {
                            $('tier_price_row_' + data.index + '_delete_button').remove();
                            $('tier_price_row_' + data.index + '_ebaymultiaccount_attribute').disabled = true;
                            $('tier_price_row_' + data.index + '_ebaymultiaccount_attribute_hidden').value = data.ebaymultiaccount_attribute;
                            $('tier_price_row_' + data.index + '_ebaymultiaccount_required').value    = data.required;
                        }

                        if (data.readOnly == '1') {
                            ['website', 'cust_group', 'qty', 'price', 'delete'].each(function(idx){
                                $('tier_price_row_'+data.index+'_'+idx).disabled = true;
                            });
                            $('tier_price_row_'+data.index+'_delete_button').hide();
                        }

                        <?php if ($_readonly): ?>
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(this.disableElement);
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button').each(this.disableElement);
                        <?php else: ?>
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(function(el){ Event.observe(el, 'change', el.setHasChanges.bind(el)); });
                        <?php endif; ?>
                        requiredAttributeControl.setEbayMultiAccountAttributeType(ebaymultiaccountAttribute, data.index);
                        if(data.default!=''){
                            var enumVal = ebaymultiaccountAttribute.options[data.index].getAttribute('enum_val');
                            var text = $('tier_price_row_'+data.index+'_default_text');
                            var select = $('tier_price_row_'+data.index+'_default_select');
                            var textarea = $('tier_price_row_'+data.index+'_default_textarea');
                            select.value = data.default;
                            text.value = data.default;
                            textarea.value = data.default.slice(1,-1);
                            requiredAttributeControl.showDefaultField(magentoAttribute, data.index);
                        }
                    },
                    disableElement: function(el) {
                        el.disabled = true;
                        el.addClassName('disabled');
                    },
                    deleteItem: function(event) {
                        var tr = Event.findElement(event, 'tr');
                        if (tr) {
                            Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                            Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                            Element.hide(tr);
                            Element.addClassName(tr, 'no-display template');
                        }
                        return false;
                    },
                    showDefaultField: function (e, index) {
                        var checkdefault = e.options[e.selectedIndex].getAttribute('value');
                        var text = $('tier_price_row_'+index+'_default_text');
                        var select = $('tier_price_row_'+index+'_default_select');
                        var textarea = $('tier_price_row_' + index + '_default_textarea');
                        var addMultiAttrButton = $('tier_price_row_' + index + '_add_multiattr_button');
                        var ebaymultiaccountAttribute = $('tier_price_row_' + index + '_ebaymultiaccount_attribute');

                        if(checkdefault == 'default'){
                            var enumVal = ebaymultiaccountAttribute.options[ebaymultiaccountAttribute.selectedIndex].getAttribute('enum_val');
                            if(enumVal){
                                select.enable();
                                select.show();
                            }
                            else{
                                text.enable();
                                text.show();
                            }

                            var attrKey = ebaymultiaccountAttribute.value;
                            if(attrKey == 'description') {
                                textarea.enable();
                                textarea.show();
                                text.hide();
                                text.disable();
                                addMultiAttrButton.show();
                                addMultiAttrButton.enable();
                            } else {
                                textarea.disable();
                                textarea.hide();
                                addMultiAttrButton.hide();
                                addMultiAttrButton.disable();
                            }
                        }else{
                            select.hide();
                            text.hide();
                            select.disable();
                            text.disable();
                            textarea.disable();
                            textarea.hide();
                            var attrKey = ebaymultiaccountAttribute.value;
                            if(attrKey == 'description') {
                                addMultiAttrButton.hide();
                                addMultiAttrButton.disable();
                            }
                        }
                    },
                    setEbayMultiAccountAttributeType: function(e, index) {
                        if(e.selectedIndex!=-1){
                            var attributeType = e.options[e.selectedIndex].getAttribute('attribute_type');
                            $('tier_price_row_' + index + '_ebaymultiaccount_attribute_type').value    = attributeType;
                            var enumVal = e.options[e.selectedIndex].getAttribute('enum_val');
                            var text = $('tier_price_row_'+index+'_default_text');
                            var select = $('tier_price_row_'+index+'_default_select');
                            select.hide();
                            text.hide();
                            select.disable();
                            text.disable();

                            if(enumVal){
                                var values = enumVal.split(",");
                                while (select.options.length > 0) {
                                    select.remove(0);
                                }
                                for ( i=0; i<values.length; i++) {
                                    select.insert(new Element('option', {"value": values[i]}).update(values[i]));
                                }
                            }
                        }
                    },
                    mapMultiAttribute: function (self) {
                        var id = self.getAttribute("row_id");
                        var idPrefix = self.getAttribute("id_prefix");

                        var defValue = $(idPrefix + id + "_default_textarea").value;
                        var attributeToAddElement = $('attribute_template');
                        if(attributeToAddElement) {
                            attributeToAddElement.value = defValue;
                        }

                        var options = {
                            type: 'popup',
                            responsive: true,
                            innerScroll: true,
                            title: '<?php echo __("Merge Multiple Attributes") ?>',
                            buttons: [{
                                text: jQuery.mage.__('Save'),
                                class: '',
                                click: function () {
                                    requiredAttributeControl.saveMultiAttributeTemp(id, idPrefix);
                                    this.closeModal();
                                }
                            }]
                        };
                        var popup = modal(options, jQuery('#popup-modal-custom'));
                        popup.openModal();

                    },
                    insertAttribute: function (event) {
                        var attributeToAddElement = $('attribute_to_add');
                        var attributeTemplateElement = $('attribute_template');
                        mapping = attributeTemplateElement.value;
                        if(attributeToAddElement) {
                            var attributeToAdd = attributeToAddElement.value;
                            mapping = mapping + "##" + attributeToAdd + "##";
                            attributeTemplateElement.value = mapping;
                        }
                    },
                    saveMultiAttributeTemp: function (id, idPrefix) {
                        if (id !== null) {
                            var attributeTemplateText = $('attribute_template').value;
                            var confAttribute = $(idPrefix+id+'_default_textarea');
                            confAttribute.value = '';
                            if (attributeTemplateText){
                                confAttribute.value = attributeTemplateText;
                            }
                        }
                    }
                };
                <?php if(count($this->getMappedAttribute()) > 0 ) {
                    $allAttrs = $this->getMappedAttribute();
                    foreach ($allAttrs as $_item) {
                    $default = isset($_item['default']) ? $_item['default']: '';
                    if($_item['ebaymultiaccount_attribute_name'] == 'description' && $default != '') {
                        $default = json_encode($default);
                    }
                ?>
                requiredAttributeControl.addItem('<?php echo $_item['ebaymultiaccount_attribute_name'] ?>', '<?php echo $_item['magento_attribute_code'] ?>', '<?php echo $_item['ebaymultiaccount_attribute_type'] ?>','<?php echo $_item['required'] ?>' ,'<?php echo $default; ?>');
                <?php } } ?>
                <?php if ($_readonly): ?>
                $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button')
                    .each(requiredAttributeControl.disableElement);
                <?php endif; ?>
                window.requiredAttributeControl = requiredAttributeControl;
//]]>
            });
        </script>
    </div>
</div>

<?php $_htmlId = 'multiAttributeOption';
$_htmlNameOption = "multiAttributeMapping";
?>
<div id="popup-modal-custom" style="display: none;">
    <div class="field admin__scope-old" id="attribute-<?php /* @escapeNotVerified */
    echo $_htmlId ?>-container" data-attribute-code="<?php /* @escapeNotVerified */
    echo $_htmlId ?>"
    >
        <div class="control">
            <div id="multi_attribute_form" class="fieldset ">
                <div class="hor-scroll" id="ebaymultiaccount_multi_attribute">
                    <table class="admin__control-table tiers_table" id="tiers_table">
                        <thead>
                        <tr>
                            <th class="col-qty required"><?php /* @escapeNotVerified */
                                echo __('Magento Attribute Option') ?></th>
                            <th class="col-delete"><?php /* @escapeNotVerified */
                                echo __('Action') ?></th>
                        </tr>
                        </thead>
                        <tbody id="<?php /* @escapeNotVerified */
                        echo $_htmlId ?>_container">
                        <textarea name="attribute_template" id="attribute_template" rows="10" cols="90"></textarea>
                        <tr class="attribute_option_row" row_id="<%- data.index %>">
                            <td>
                                <select name="attribute_to_add" id="attribute_to_add">
                                    <?php foreach ($this->getMagentoAttributes() as $_groupId=>$_groupName): ?>
                                        <?php if($_groupId != '' && $_groupId != 'default') { ?>
                                            <option value='<?php echo $_groupId ?>' ><?php echo __($_groupName) ?></option>
                                        <?php } ?>
                                    <?php endforeach ?>
                                </select>
                            </td>
                            <td class="col-delete"><input type="hidden" name="<?php /* @escapeNotVerified */ echo $_htmlNameOption ?>[<%- data.index %>][delete]" class="delete" value="" id="option_<%- data.index %>_delete" />
                                <button title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Add Attribute')); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="option_<%- data.index %>_delete_button" onclick="return requiredAttributeControl.insertAttribute(event);">
                                    <span><?php /* @escapeNotVerified */ echo __("Add Attribute") ?></span>
                                </button>
                            </td>
                        </tr>
                        </tbody>
                        <tfoot>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>